services:
  ai-agent:
    build: .
    env_file:
      - .env
    volumes:
      - ./api:/src/api  # ディレクトリ部分のみマウントする
      - ./models:/src/models  
    ports:
      - 8000:8000 # ホストマシンのポート8000を、docker内のポート8000に接続する
